  
version: '3.1'

services:
  otusdb:
    container_name: otus_mysql
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: otus_word
      MYSQL_USER: otus
      MYSQL_PASSWORD: 12345
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./custom.conf:/etc/mysql/conf.d
    expose:
      - "3306"
    ports:
      - "3309:3306"
    networks:
      - mysql-ntw

  phpmyadmin:
    container_name: otus_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 11989:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: otus_mysql
      PMA_USER: root
      PMA_PORT: 3306
      PMA_PASSWORD: 12345
    networks:
      - mysql-ntw
  


volumes:
  data:
networks:
  mysql-ntw:
    name: mysql-ntw
    driver: bridge