// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wc.Impl;

namespace Wc.Impl.Migrations
{
    [DbContext(typeof(WordsCounterDbContext))]
    [Migration("20210528144114_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Wc.Impl.DocumentSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("DocumentUuid")
                        .HasColumnType("integer");

                    b.Property<string[]>("Vector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text[]")
                        .HasComputedColumnSql("tsvector_to_array(to_tsvector('english_hunspell',Content))", true);

                    b.HasKey("Id");

                    b.ToTable("DocumentSource");
                });
#pragma warning restore 612, 618
        }
    }
}
